---
- name: Download Grafana .deb package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.4.2_amd64.deb
    dest: /tmp/grafana.deb

- name: Install Grafana via dpkg
  apt:
    deb: /tmp/grafana.deb

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: true
    state: started

- import_tasks: provisioning.yml