---
- name: Copy Elasticsearch .deb package
  ansible.builtin.copy:
    src: elasticsearch-8.11.0-amd64.deb
    dest: /tmp/elasticsearch.deb
    mode: "0644"

- name: Install Elasticsearch from local .deb
  ansible.builtin.apt:
    deb: /tmp/elasticsearch.deb

- name: Ensure Elasticsearch config directory exists
  ansible.builtin.file:
    path: /etc/elasticsearch
    state: directory
    mode: '0755'

- name: Deploy elasticsearch.yml configuration
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'

- name: Reload systemd daemon (in case unit file is new)
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started
