- name: Configure stub_status in /etc/nginx/conf.d/stub_status.conf
  copy:
    dest: /etc/nginx/conf.d/stub_status.conf
    content: |
      server {
        listen 8080;
        server_name localhost;

        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            deny all;
        }
      }
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx